"""
Seed script for DermaGenie database.
Populates ingredients, products, and skin conditions tables.

Usage:
    python -m app.seed.seed_data
"""

import asyncio
from sqlalchemy import select
from app.database import engine, async_session_maker, Base
from app.models import Ingredient, Product, SkinCondition


# ═══════════════════════════════════════════════════════════
# INGREDIENTS (80+ entries)
# ═══════════════════════════════════════════════════════════
INGREDIENTS_DATA = [
    # ── Humectants ──
    {"ingredient_name": "Hyaluronic Acid", "category": "Humectant", "benefits": "Attracts and retains moisture, plumps skin, reduces fine lines", "risks": "May cause dryness in very dry climates without occlusive", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.5, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Glycerin", "category": "Humectant", "benefits": "Moisturizes, strengthens skin barrier, non-irritating", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.2, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Sodium Hyaluronate", "category": "Humectant", "benefits": "Smaller molecule form of hyaluronic acid, penetrates deeper", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.3, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Propylene Glycol", "category": "Humectant", "benefits": "Hydrates skin, enhances product absorption", "risks": "May cause irritation in sensitive individuals", "recommended_skin_types": ["Oily", "Combination", "Normal"], "avoid_skin_types": ["Sensitive"], "severity_score": 3.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Butylene Glycol", "category": "Humectant", "benefits": "Lightweight moisturizer, helps product absorption", "risks": "Generally well tolerated", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal"], "avoid_skin_types": [], "severity_score": 1.0, "is_natural": False, "comedogenic_rating": 1},
    {"ingredient_name": "Urea", "category": "Humectant", "benefits": "Deep hydration, exfoliates dead skin cells, smooths rough skin", "risks": "May sting on broken skin", "recommended_skin_types": ["Dry", "Normal"], "avoid_skin_types": ["Sensitive"], "severity_score": 2.5, "is_natural": False, "comedogenic_rating": 0},

    # ── Emollients ──
    {"ingredient_name": "Ceramides", "category": "Emollient", "benefits": "Restores skin barrier, locks in moisture, protects against irritants", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.2, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Squalane", "category": "Emollient", "benefits": "Lightweight moisturizer, antioxidant, non-comedogenic", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.3, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Jojoba Oil", "category": "Emollient", "benefits": "Mimics natural sebum, balances oil production, moisturizes", "risks": "May worsen acne in some individuals", "recommended_skin_types": ["Dry", "Normal", "Combination"], "avoid_skin_types": [], "severity_score": 1.0, "is_natural": True, "comedogenic_rating": 2},
    {"ingredient_name": "Shea Butter", "category": "Emollient", "benefits": "Rich moisturizer, anti-inflammatory, skin barrier repair", "risks": "May be too heavy for oily skin", "recommended_skin_types": ["Dry", "Normal"], "avoid_skin_types": ["Oily"], "severity_score": 1.5, "is_natural": True, "comedogenic_rating": 2},
    {"ingredient_name": "Dimethicone", "category": "Emollient", "benefits": "Creates protective barrier, smooths skin, non-comedogenic", "risks": "May trap irritants under the skin", "recommended_skin_types": ["Dry", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 1.0, "is_natural": False, "comedogenic_rating": 1},
    {"ingredient_name": "Petrolatum", "category": "Emollient", "benefits": "Excellent occlusive, locks in moisture, protects skin barrier", "risks": "May feel greasy, can trap bacteria on unclean skin", "recommended_skin_types": ["Dry", "Normal"], "avoid_skin_types": ["Oily"], "severity_score": 1.5, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Coconut Oil", "category": "Emollient", "benefits": "Moisturizes, antimicrobial properties", "risks": "Highly comedogenic, can clog pores and cause breakouts", "recommended_skin_types": ["Dry"], "avoid_skin_types": ["Oily", "Combination"], "severity_score": 3.0, "is_natural": True, "comedogenic_rating": 4},

    # ── Active Ingredients ──
    {"ingredient_name": "Niacinamide", "category": "Active", "benefits": "Reduces pore size, controls oil, fades dark spots, strengthens barrier", "risks": "May cause flushing at high concentrations", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.8, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Retinol", "category": "Active", "benefits": "Anti-aging, boosts collagen, reduces wrinkles and fine lines", "risks": "Causes dryness, peeling, sun sensitivity. Not for sensitive skin beginners", "recommended_skin_types": ["Oily", "Combination", "Normal"], "avoid_skin_types": ["Sensitive"], "severity_score": 5.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Salicylic Acid", "category": "Active", "benefits": "Unclogs pores, exfoliates, reduces acne and blackheads", "risks": "Can cause dryness and irritation, especially at high concentrations", "recommended_skin_types": ["Oily", "Combination"], "avoid_skin_types": ["Dry", "Sensitive"], "severity_score": 4.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Glycolic Acid", "category": "Active", "benefits": "Exfoliates dead skin cells, brightens skin, reduces hyperpigmentation", "risks": "Can cause irritation, sun sensitivity, not for sensitive skin", "recommended_skin_types": ["Oily", "Combination", "Normal"], "avoid_skin_types": ["Sensitive", "Dry"], "severity_score": 5.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Lactic Acid", "category": "Active", "benefits": "Gentle exfoliant, hydrates while exfoliating, brightens skin", "risks": "Mild tingling, sun sensitivity", "recommended_skin_types": ["Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 3.0, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Vitamin C", "category": "Active", "benefits": "Antioxidant, brightens skin, fades dark spots, boosts collagen", "risks": "Can oxidize, may cause tingling on sensitive skin", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal"], "avoid_skin_types": [], "severity_score": 2.0, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Ascorbic Acid", "category": "Active", "benefits": "Pure form of Vitamin C, potent antioxidant, collagen synthesis", "risks": "Unstable, can irritate sensitive skin", "recommended_skin_types": ["Oily", "Combination", "Normal"], "avoid_skin_types": ["Sensitive"], "severity_score": 3.5, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Benzoyl Peroxide", "category": "Active", "benefits": "Kills acne-causing bacteria, reduces inflammation", "risks": "Very drying, can bleach fabrics, causes peeling", "recommended_skin_types": ["Oily"], "avoid_skin_types": ["Dry", "Sensitive"], "severity_score": 7.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Azelaic Acid", "category": "Active", "benefits": "Reduces acne, fades hyperpigmentation, anti-inflammatory", "risks": "Mild tingling initially", "recommended_skin_types": ["Oily", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 2.0, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Alpha Arbutin", "category": "Active", "benefits": "Brightens skin, fades dark spots, inhibits melanin production", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.5, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Tranexamic Acid", "category": "Active", "benefits": "Reduces hyperpigmentation, melasma treatment, brightening", "risks": "Minimal risks when used topically", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 1.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Kojic Acid", "category": "Active", "benefits": "Skin brightening, inhibits melanin, fades dark spots", "risks": "May cause contact dermatitis in sensitive individuals", "recommended_skin_types": ["Oily", "Combination", "Normal"], "avoid_skin_types": ["Sensitive"], "severity_score": 3.5, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Bakuchiol", "category": "Active", "benefits": "Natural retinol alternative, anti-aging without irritation", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.5, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Zinc PCA", "category": "Active", "benefits": "Controls oil production, reduces acne, anti-inflammatory", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Combination"], "avoid_skin_types": [], "severity_score": 0.5, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Peptides", "category": "Active", "benefits": "Stimulates collagen production, firms skin, reduces wrinkles", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.3, "is_natural": False, "comedogenic_rating": 0},

    # ── Botanicals & Naturals ──
    {"ingredient_name": "Aloe Vera", "category": "Botanical", "benefits": "Soothes irritation, hydrates, anti-inflammatory, wound healing", "risks": "Rare allergic reactions", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.3, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Tea Tree Oil", "category": "Botanical", "benefits": "Antimicrobial, reduces acne, anti-inflammatory", "risks": "Can be irritating if used undiluted, allergic reactions possible", "recommended_skin_types": ["Oily", "Combination"], "avoid_skin_types": ["Sensitive", "Dry"], "severity_score": 4.0, "is_natural": True, "comedogenic_rating": 1},
    {"ingredient_name": "Green Tea Extract", "category": "Botanical", "benefits": "Antioxidant, anti-inflammatory, reduces redness, protects against UV", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.3, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Centella Asiatica", "category": "Botanical", "benefits": "Wound healing, calms irritation, strengthens skin barrier", "risks": "Rare allergic reactions", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.2, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Chamomile Extract", "category": "Botanical", "benefits": "Anti-inflammatory, soothes irritation, calming", "risks": "Possible allergy in ragweed-sensitive individuals", "recommended_skin_types": ["Dry", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.5, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Rosehip Oil", "category": "Botanical", "benefits": "Rich in vitamins A and C, reduces scars, hydrates", "risks": "May cause breakouts in acne-prone skin", "recommended_skin_types": ["Dry", "Normal", "Combination"], "avoid_skin_types": ["Oily"], "severity_score": 1.5, "is_natural": True, "comedogenic_rating": 1},
    {"ingredient_name": "Witch Hazel", "category": "Botanical", "benefits": "Astringent, reduces pore size, anti-inflammatory", "risks": "Can be drying, some formulations contain alcohol", "recommended_skin_types": ["Oily", "Combination"], "avoid_skin_types": ["Dry", "Sensitive"], "severity_score": 3.5, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Turmeric Extract", "category": "Botanical", "benefits": "Anti-inflammatory, antioxidant, brightens skin", "risks": "May stain skin temporarily", "recommended_skin_types": ["Oily", "Combination", "Normal"], "avoid_skin_types": [], "severity_score": 1.5, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Licorice Root Extract", "category": "Botanical", "benefits": "Brightens skin, fades dark spots, anti-inflammatory, soothes redness", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.3, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Calendula Extract", "category": "Botanical", "benefits": "Soothes, heals, anti-inflammatory, gentle on sensitive skin", "risks": "Possible allergy in daisy-family sensitive individuals", "recommended_skin_types": ["Dry", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.3, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Snail Mucin", "category": "Botanical", "benefits": "Hydrates, promotes cell repair, fades scars, anti-aging", "risks": "Rare allergic reactions", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.5, "is_natural": True, "comedogenic_rating": 0},

    # ── Sunscreen Actives ──
    {"ingredient_name": "Zinc Oxide", "category": "Sunscreen", "benefits": "Broad spectrum UV protection, anti-inflammatory, non-irritating", "risks": "May leave white cast", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.3, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Titanium Dioxide", "category": "Sunscreen", "benefits": "Physical UV blocker, gentle on skin", "risks": "May leave white cast", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.3, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Avobenzone", "category": "Sunscreen", "benefits": "UVA protection", "risks": "Can degrade in sunlight, may cause irritation", "recommended_skin_types": ["Oily", "Combination", "Normal"], "avoid_skin_types": ["Sensitive"], "severity_score": 3.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Octinoxate", "category": "Sunscreen", "benefits": "UVB protection", "risks": "Hormone disruption concerns, coral reef harm", "recommended_skin_types": ["Oily", "Normal"], "avoid_skin_types": ["Sensitive"], "severity_score": 4.0, "is_natural": False, "comedogenic_rating": 0},

    # ── Antioxidants ──
    {"ingredient_name": "Vitamin E", "category": "Antioxidant", "benefits": "Protects from free radicals, moisturizes, heals scars", "risks": "May cause breakouts in acne-prone skin", "recommended_skin_types": ["Dry", "Normal", "Combination"], "avoid_skin_types": [], "severity_score": 1.0, "is_natural": True, "comedogenic_rating": 2},
    {"ingredient_name": "Resveratrol", "category": "Antioxidant", "benefits": "Anti-aging, protects against environmental damage", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal"], "avoid_skin_types": [], "severity_score": 0.5, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Ferulic Acid", "category": "Antioxidant", "benefits": "Enhances vitamin C stability, antioxidant protection, anti-aging", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal"], "avoid_skin_types": [], "severity_score": 0.5, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Coenzyme Q10", "category": "Antioxidant", "benefits": "Anti-aging, reduces oxidative damage, energizes skin cells", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal"], "avoid_skin_types": [], "severity_score": 0.3, "is_natural": True, "comedogenic_rating": 0},

    # ── Preservatives & Potentially Irritating ──
    {"ingredient_name": "Alcohol Denat", "category": "Solvent", "benefits": "Helps product absorption, creates matte finish", "risks": "Very drying, damages skin barrier, causes irritation", "recommended_skin_types": [], "avoid_skin_types": ["Dry", "Sensitive"], "severity_score": 7.5, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Fragrance", "category": "Fragrance", "benefits": "Pleasant scent experience", "risks": "Major irritant, causes allergic reactions, sensitization, contact dermatitis", "recommended_skin_types": [], "avoid_skin_types": ["Sensitive", "Dry"], "severity_score": 7.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Essential Oils", "category": "Fragrance", "benefits": "Natural fragrance, some therapeutic properties", "risks": "Can cause irritation, photosensitivity, allergic reactions", "recommended_skin_types": ["Normal"], "avoid_skin_types": ["Sensitive", "Dry"], "severity_score": 5.5, "is_natural": True, "comedogenic_rating": 1},
    {"ingredient_name": "Sodium Lauryl Sulfate", "category": "Surfactant", "benefits": "Strong cleansing, creates lather", "risks": "Very harsh, strips natural oils, damages skin barrier", "recommended_skin_types": [], "avoid_skin_types": ["Dry", "Sensitive", "Normal", "Combination"], "severity_score": 8.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Sodium Laureth Sulfate", "category": "Surfactant", "benefits": "Cleansing, gentler than SLS", "risks": "Still drying, may irritate sensitive skin", "recommended_skin_types": ["Oily"], "avoid_skin_types": ["Dry", "Sensitive"], "severity_score": 5.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Parabens", "category": "Preservative", "benefits": "Effective preservative, prevents bacterial growth", "risks": "Endocrine disruption concerns, allergic reactions possible", "recommended_skin_types": [], "avoid_skin_types": ["Sensitive"], "severity_score": 5.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Phenoxyethanol", "category": "Preservative", "benefits": "Effective preservative, generally well tolerated", "risks": "May irritate at high concentrations", "recommended_skin_types": ["Oily", "Combination", "Normal"], "avoid_skin_types": [], "severity_score": 2.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Methylisothiazolinone", "category": "Preservative", "benefits": "Broad spectrum preservative", "risks": "High allergen potential, banned in leave-on products in EU", "recommended_skin_types": [], "avoid_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "severity_score": 9.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Formaldehyde", "category": "Preservative", "benefits": "Antimicrobial preservative", "risks": "Known carcinogen, strong irritant, allergenic", "recommended_skin_types": [], "avoid_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "severity_score": 10.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Mineral Oil", "category": "Emollient", "benefits": "Locks in moisture, inexpensive", "risks": "Can clog pores, may contain impurities", "recommended_skin_types": ["Dry"], "avoid_skin_types": ["Oily", "Combination"], "severity_score": 3.5, "is_natural": False, "comedogenic_rating": 2},
    {"ingredient_name": "Isopropyl Myristate", "category": "Emollient", "benefits": "Skin softener, enhances absorption", "risks": "Highly comedogenic, clogs pores", "recommended_skin_types": [], "avoid_skin_types": ["Oily", "Combination"], "severity_score": 4.0, "is_natural": False, "comedogenic_rating": 5},

    # ── Additional Actives & Specialty ──
    {"ingredient_name": "Panthenol", "category": "Active", "benefits": "Vitamin B5 derivative, hydrates, soothes, promotes healing", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.2, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Allantoin", "category": "Active", "benefits": "Soothes irritation, promotes cell regeneration, moisturizes", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.2, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Madecassoside", "category": "Active", "benefits": "From Centella, calms inflammation, promotes wound healing", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.2, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Colloidal Oatmeal", "category": "Active", "benefits": "Soothes itching, anti-inflammatory, moisturizes", "risks": "Rare allergic reactions in oat-sensitive individuals", "recommended_skin_types": ["Dry", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.3, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Sulfur", "category": "Active", "benefits": "Antibacterial, reduces acne and fungal infections", "risks": "Drying, strong smell", "recommended_skin_types": ["Oily"], "avoid_skin_types": ["Dry", "Sensitive"], "severity_score": 5.5, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Hydroquinone", "category": "Active", "benefits": "Potent skin lightener, treats hyperpigmentation", "risks": "Can cause ochronosis with prolonged use, irritation, sun sensitivity", "recommended_skin_types": [], "avoid_skin_types": ["Sensitive"], "severity_score": 7.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Adapalene", "category": "Active", "benefits": "Retinoid for acne treatment, less irritating than tretinoin", "risks": "Dryness, peeling, sun sensitivity initially", "recommended_skin_types": ["Oily", "Combination"], "avoid_skin_types": ["Dry", "Sensitive"], "severity_score": 5.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Mandelic Acid", "category": "Active", "benefits": "Gentle AHA, brightens, antibacterial, suitable for darker skin tones", "risks": "Mild sun sensitivity", "recommended_skin_types": ["Oily", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 2.0, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Polyhydroxy Acids", "category": "Active", "benefits": "Gentle exfoliation, hydration, antioxidant, suitable for sensitive skin", "risks": "Minimal risks", "recommended_skin_types": ["Dry", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 1.0, "is_natural": False, "comedogenic_rating": 0},
    {"ingredient_name": "Bentonite Clay", "category": "Active", "benefits": "Absorbs excess oil, unclogs pores, detoxifies skin", "risks": "Can be very drying", "recommended_skin_types": ["Oily", "Combination"], "avoid_skin_types": ["Dry", "Sensitive"], "severity_score": 4.0, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Kaolin Clay", "category": "Active", "benefits": "Gentle oil absorption, suitable for sensitive skin", "risks": "Can be drying with overuse", "recommended_skin_types": ["Oily", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 1.5, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Charcoal", "category": "Active", "benefits": "Draws out impurities, deep cleanses pores", "risks": "Can be drying and stripping", "recommended_skin_types": ["Oily", "Combination"], "avoid_skin_types": ["Dry", "Sensitive"], "severity_score": 3.5, "is_natural": True, "comedogenic_rating": 0},

    # ── Miscellaneous ──
    {"ingredient_name": "Tocopherol", "category": "Antioxidant", "benefits": "Vitamin E form, antioxidant protection, moisturizing", "risks": "Minimal for most", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal"], "avoid_skin_types": [], "severity_score": 0.5, "is_natural": True, "comedogenic_rating": 1},
    {"ingredient_name": "Citric Acid", "category": "pH Adjuster", "benefits": "pH balancing, mild exfoliation, antioxidant", "risks": "May irritate at high concentrations", "recommended_skin_types": ["Oily", "Combination", "Normal"], "avoid_skin_types": ["Sensitive"], "severity_score": 2.0, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Xanthan Gum", "category": "Thickener", "benefits": "Texturizer, stabilizer, non-irritating", "risks": "Minimal risks", "recommended_skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "avoid_skin_types": [], "severity_score": 0.1, "is_natural": True, "comedogenic_rating": 0},
    {"ingredient_name": "Stearic Acid", "category": "Emollient", "benefits": "Emollient, surfactant, thickener", "risks": "May clog pores in acne-prone skin", "recommended_skin_types": ["Dry", "Normal"], "avoid_skin_types": ["Oily"], "severity_score": 1.5, "is_natural": True, "comedogenic_rating": 2},
    {"ingredient_name": "Cetyl Alcohol", "category": "Emollient", "benefits": "Fatty alcohol, emollient, thickener, non-drying", "risks": "Generally safe, may irritate very sensitive skin", "recommended_skin_types": ["Dry", "Normal", "Combination"], "avoid_skin_types": [], "severity_score": 0.8, "is_natural": False, "comedogenic_rating": 2},
    {"ingredient_name": "Cetearyl Alcohol", "category": "Emollient", "benefits": "Emollient, emulsifier, product stabilizer", "risks": "Generally safe", "recommended_skin_types": ["Dry", "Normal", "Combination"], "avoid_skin_types": [], "severity_score": 0.5, "is_natural": False, "comedogenic_rating": 2},
]


# ═══════════════════════════════════════════════════════════
# PRODUCTS (40+ entries)
# ═══════════════════════════════════════════════════════════
PRODUCTS_DATA = [
    # ── Cleansers ──
    {"product_name": "CeraVe Hydrating Facial Cleanser", "brand": "CeraVe", "category": "Cleanser", "description": "Gentle, non-foaming cleanser with ceramides and hyaluronic acid", "key_ingredients": ["Ceramides", "Hyaluronic Acid", "Glycerin"], "skin_types": ["Dry", "Normal", "Sensitive"], "skin_concerns": ["Dryness", "Irritation"], "price_range": "$", "usage_frequency": "Twice Daily", "expected_results": "1-2 Weeks"},
    {"product_name": "CeraVe Foaming Facial Cleanser", "brand": "CeraVe", "category": "Cleanser", "description": "Oil-controlling foaming cleanser with niacinamide", "key_ingredients": ["Ceramides", "Niacinamide", "Hyaluronic Acid"], "skin_types": ["Oily", "Combination", "Normal"], "skin_concerns": ["Acne", "Blackheads", "Oily Skin"], "price_range": "$", "usage_frequency": "Twice Daily", "expected_results": "1-2 Weeks"},
    {"product_name": "La Roche-Posay Toleriane Hydrating Cleanser", "brand": "La Roche-Posay", "category": "Cleanser", "description": "Ultra-gentle cleanser for sensitive skin", "key_ingredients": ["Ceramide-3", "Niacinamide", "Glycerin"], "skin_types": ["Dry", "Normal", "Sensitive"], "skin_concerns": ["Irritation", "Redness", "Dryness"], "price_range": "$$", "usage_frequency": "Twice Daily", "expected_results": "1 Week"},
    {"product_name": "Neutrogena Oil-Free Acne Wash", "brand": "Neutrogena", "category": "Cleanser", "description": "Salicylic acid acne-fighting cleanser", "key_ingredients": ["Salicylic Acid"], "skin_types": ["Oily", "Combination"], "skin_concerns": ["Acne", "Pimples", "Blackheads"], "price_range": "$", "usage_frequency": "Once or Twice Daily", "expected_results": "2-4 Weeks"},
    {"product_name": "Cetaphil Gentle Skin Cleanser", "brand": "Cetaphil", "category": "Cleanser", "description": "Mild, non-irritating cleanser for all skin types", "key_ingredients": ["Glycerin", "Panthenol"], "skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "skin_concerns": ["Irritation", "Dryness"], "price_range": "$", "usage_frequency": "Twice Daily", "expected_results": "1 Week"},

    # ── Moisturizers ──
    {"product_name": "CeraVe Moisturizing Cream", "brand": "CeraVe", "category": "Moisturizer", "description": "Rich cream with ceramides and MVE technology for 24-hour hydration", "key_ingredients": ["Ceramides", "Hyaluronic Acid", "Petrolatum"], "skin_types": ["Dry", "Normal"], "skin_concerns": ["Dryness", "Itching"], "price_range": "$", "usage_frequency": "Twice Daily", "expected_results": "2-4 Weeks"},
    {"product_name": "Neutrogena Hydro Boost Water Gel", "brand": "Neutrogena", "category": "Moisturizer", "description": "Lightweight gel moisturizer with hyaluronic acid", "key_ingredients": ["Hyaluronic Acid", "Glycerin", "Dimethicone"], "skin_types": ["Oily", "Combination", "Normal"], "skin_concerns": ["Dryness", "Dullness"], "price_range": "$", "usage_frequency": "Twice Daily", "expected_results": "1-2 Weeks"},
    {"product_name": "La Roche-Posay Toleriane Double Repair Moisturizer", "brand": "La Roche-Posay", "category": "Moisturizer", "description": "Barrier-restoring moisturizer with ceramides and niacinamide", "key_ingredients": ["Ceramide-3", "Niacinamide", "Glycerin"], "skin_types": ["Dry", "Normal", "Sensitive"], "skin_concerns": ["Dryness", "Irritation", "Redness"], "price_range": "$$", "usage_frequency": "Twice Daily", "expected_results": "2-4 Weeks"},
    {"product_name": "Vanicream Moisturizing Skin Cream", "brand": "Vanicream", "category": "Moisturizer", "description": "Free of dyes, fragrance, and common irritants", "key_ingredients": ["Petrolatum", "Cetearyl Alcohol", "Glycerin"], "skin_types": ["Dry", "Sensitive"], "skin_concerns": ["Dryness", "Irritation", "Itching"], "price_range": "$", "usage_frequency": "As Needed", "expected_results": "1-2 Weeks"},
    {"product_name": "Tatcha The Dewy Skin Cream", "brand": "Tatcha", "category": "Moisturizer", "description": "Luxurious hydrating cream with Japanese purple rice", "key_ingredients": ["Hyaluronic Acid", "Glycerin", "Squalane"], "skin_types": ["Dry", "Normal"], "skin_concerns": ["Dryness", "Fine Lines", "Dullness"], "price_range": "$$$", "usage_frequency": "Twice Daily", "expected_results": "2-4 Weeks"},
    {"product_name": "Kiehl's Ultra Facial Cream", "brand": "Kiehl's", "category": "Moisturizer", "description": "24-hour hydrating cream with squalane and glacial glycoprotein", "key_ingredients": ["Squalane", "Glycerin"], "skin_types": ["Oily", "Dry", "Combination", "Normal"], "skin_concerns": ["Dryness", "Dullness"], "price_range": "$$", "usage_frequency": "Twice Daily", "expected_results": "2 Weeks"},

    # ── Sunscreens ──
    {"product_name": "EltaMD UV Clear SPF 46", "brand": "EltaMD", "category": "Sunscreen", "description": "Lightweight sunscreen with niacinamide, great for acne-prone skin", "key_ingredients": ["Zinc Oxide", "Niacinamide", "Hyaluronic Acid"], "skin_types": ["Oily", "Combination", "Sensitive"], "skin_concerns": ["Acne", "Hyperpigmentation", "Redness"], "price_range": "$$", "usage_frequency": "Every Morning", "expected_results": "Immediate Protection"},
    {"product_name": "La Roche-Posay Anthelios Melt-In Sunscreen SPF 60", "brand": "La Roche-Posay", "category": "Sunscreen", "description": "Broad spectrum protection with antioxidants", "key_ingredients": ["Avobenzone", "Vitamin E"], "skin_types": ["Oily", "Dry", "Combination", "Normal"], "skin_concerns": ["Hyperpigmentation", "Fine Lines"], "price_range": "$$", "usage_frequency": "Every Morning", "expected_results": "Immediate Protection"},
    {"product_name": "Neutrogena Hydro Boost SPF 50", "brand": "Neutrogena", "category": "Sunscreen", "description": "Hydrating sunscreen with hyaluronic acid", "key_ingredients": ["Hyaluronic Acid", "Glycerin"], "skin_types": ["Oily", "Combination", "Normal"], "skin_concerns": ["Dryness", "Sun Damage"], "price_range": "$", "usage_frequency": "Every Morning", "expected_results": "Immediate Protection"},
    {"product_name": "CeraVe Hydrating Mineral Sunscreen SPF 30", "brand": "CeraVe", "category": "Sunscreen", "description": "Mineral sunscreen with ceramides", "key_ingredients": ["Zinc Oxide", "Titanium Dioxide", "Ceramides"], "skin_types": ["Dry", "Normal", "Sensitive"], "skin_concerns": ["Dryness", "Sun Protection"], "price_range": "$", "usage_frequency": "Every Morning", "expected_results": "Immediate Protection"},
    {"product_name": "Supergoop Unseen Sunscreen SPF 40", "brand": "Supergoop", "category": "Sunscreen", "description": "Invisible, weightless sunscreen primer", "key_ingredients": ["Avobenzone", "Dimethicone"], "skin_types": ["Oily", "Combination", "Normal"], "skin_concerns": ["Oily Skin", "Makeup Base"], "price_range": "$$", "usage_frequency": "Every Morning", "expected_results": "Immediate Protection"},

    # ── Serums & Treatments ──
    {"product_name": "The Ordinary Niacinamide 10% + Zinc 1%", "brand": "The Ordinary", "category": "Serum", "description": "Oil-controlling serum that reduces blemishes and pore appearance", "key_ingredients": ["Niacinamide", "Zinc PCA"], "skin_types": ["Oily", "Combination"], "skin_concerns": ["Acne", "Pimples", "Blackheads", "Uneven Skin Tone"], "price_range": "$", "usage_frequency": "Twice Daily", "expected_results": "4-8 Weeks"},
    {"product_name": "The Ordinary Hyaluronic Acid 2% + B5", "brand": "The Ordinary", "category": "Serum", "description": "Multi-depth hydration serum with hyaluronic acid", "key_ingredients": ["Hyaluronic Acid", "Sodium Hyaluronate", "Panthenol"], "skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "skin_concerns": ["Dryness", "Fine Lines"], "price_range": "$", "usage_frequency": "Twice Daily", "expected_results": "2-4 Weeks"},
    {"product_name": "Paula's Choice 2% BHA Liquid Exfoliant", "brand": "Paula's Choice", "category": "Exfoliant", "description": "Leave-on salicylic acid exfoliant for unclogging pores", "key_ingredients": ["Salicylic Acid", "Green Tea Extract"], "skin_types": ["Oily", "Combination", "Normal"], "skin_concerns": ["Acne", "Blackheads", "Whiteheads", "Uneven Skin Tone"], "price_range": "$$", "usage_frequency": "Once or Twice Daily", "expected_results": "4-6 Weeks"},
    {"product_name": "The Ordinary Alpha Arbutin 2% + HA", "brand": "The Ordinary", "category": "Serum", "description": "Brightening serum targeting dark spots and uneven skin tone", "key_ingredients": ["Alpha Arbutin", "Hyaluronic Acid"], "skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "skin_concerns": ["Dark Spots", "Hyperpigmentation", "Uneven Skin Tone"], "price_range": "$", "usage_frequency": "Twice Daily", "expected_results": "6-8 Weeks"},
    {"product_name": "The Ordinary Retinol 0.5% in Squalane", "brand": "The Ordinary", "category": "Treatment", "description": "Anti-aging retinol serum in a squalane base", "key_ingredients": ["Retinol", "Squalane"], "skin_types": ["Oily", "Combination", "Normal"], "skin_concerns": ["Fine Lines", "Wrinkles", "Uneven Skin Tone"], "price_range": "$", "usage_frequency": "Once Daily (PM)", "expected_results": "8-12 Weeks"},
    {"product_name": "COSRX Advanced Snail 96 Mucin Power Essence", "brand": "COSRX", "category": "Essence", "description": "Hydrating and repairing essence with 96% snail mucin", "key_ingredients": ["Snail Mucin", "Sodium Hyaluronate", "Allantoin"], "skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "skin_concerns": ["Dryness", "Dark Spots", "Fine Lines"], "price_range": "$", "usage_frequency": "Twice Daily", "expected_results": "4-6 Weeks"},
    {"product_name": "Drunk Elephant C-Firma Fresh Day Serum", "brand": "Drunk Elephant", "category": "Serum", "description": "Potent vitamin C serum with ferulic acid for brightening", "key_ingredients": ["Vitamin C", "Ferulic Acid", "Vitamin E"], "skin_types": ["Oily", "Combination", "Normal"], "skin_concerns": ["Dark Spots", "Hyperpigmentation", "Fine Lines", "Dullness"], "price_range": "$$$", "usage_frequency": "Once Daily (AM)", "expected_results": "4-8 Weeks"},
    {"product_name": "The Ordinary Azelaic Acid Suspension 10%", "brand": "The Ordinary", "category": "Treatment", "description": "Brightening and acne-fighting treatment", "key_ingredients": ["Azelaic Acid"], "skin_types": ["Oily", "Combination", "Normal", "Sensitive"], "skin_concerns": ["Acne", "Hyperpigmentation", "Redness", "Uneven Skin Tone"], "price_range": "$", "usage_frequency": "Twice Daily", "expected_results": "4-8 Weeks"},
    {"product_name": "Differin Adapalene Gel 0.1%", "brand": "Differin", "category": "Treatment", "description": "OTC retinoid for acne treatment", "key_ingredients": ["Adapalene"], "skin_types": ["Oily", "Combination"], "skin_concerns": ["Acne", "Pimples", "Blackheads", "Whiteheads"], "price_range": "$", "usage_frequency": "Once Daily (PM)", "expected_results": "8-12 Weeks"},

    # ── Toners ──
    {"product_name": "Thayers Witch Hazel Toner", "brand": "Thayers", "category": "Toner", "description": "Alcohol-free witch hazel toner with aloe vera", "key_ingredients": ["Witch Hazel", "Aloe Vera", "Glycerin"], "skin_types": ["Oily", "Combination", "Normal"], "skin_concerns": ["Acne", "Blackheads", "Pore Size"], "price_range": "$", "usage_frequency": "Twice Daily", "expected_results": "2-4 Weeks"},
    {"product_name": "COSRX AHA/BHA Clarifying Treatment Toner", "brand": "COSRX", "category": "Toner", "description": "Gentle exfoliating toner with AHA and BHA", "key_ingredients": ["Glycolic Acid", "Salicylic Acid", "Allantoin"], "skin_types": ["Oily", "Combination"], "skin_concerns": ["Acne", "Blackheads", "Uneven Skin Tone"], "price_range": "$", "usage_frequency": "Once Daily", "expected_results": "4-6 Weeks"},
    {"product_name": "Klairs Supple Preparation Unscented Toner", "brand": "Klairs", "category": "Toner", "description": "Hydrating, fragrance-free toner for sensitive skin", "key_ingredients": ["Hyaluronic Acid", "Centella Asiatica", "Panthenol"], "skin_types": ["Dry", "Normal", "Sensitive"], "skin_concerns": ["Dryness", "Irritation", "Redness"], "price_range": "$", "usage_frequency": "Twice Daily", "expected_results": "1-2 Weeks"},

    # ── Eye Creams ──
    {"product_name": "CeraVe Eye Repair Cream", "brand": "CeraVe", "category": "Eye Cream", "description": "Lightweight eye cream with ceramides and niacinamide", "key_ingredients": ["Ceramides", "Niacinamide", "Hyaluronic Acid"], "skin_types": ["Oily", "Dry", "Combination", "Normal", "Sensitive"], "skin_concerns": ["Dark Spots", "Fine Lines"], "price_range": "$", "usage_frequency": "Twice Daily", "expected_results": "4-8 Weeks"},

    # ── Masks ──
    {"product_name": "Aztec Secret Indian Healing Clay", "brand": "Aztec Secret", "category": "Face Mask", "description": "100% natural calcium bentonite clay mask", "key_ingredients": ["Bentonite Clay"], "skin_types": ["Oily", "Combination"], "skin_concerns": ["Acne", "Blackheads", "Pore Size"], "price_range": "$", "usage_frequency": "Once or Twice Weekly", "expected_results": "2-4 Weeks"},
    {"product_name": "Laneige Water Sleeping Mask", "brand": "Laneige", "category": "Sleeping Mask", "description": "Overnight hydrating mask for dewy morning skin", "key_ingredients": ["Hyaluronic Acid", "Glycerin"], "skin_types": ["Dry", "Normal", "Combination"], "skin_concerns": ["Dryness", "Dullness"], "price_range": "$$", "usage_frequency": "2-3 Times Weekly", "expected_results": "1-2 Weeks"},

    # ── Body & Specialty ──
    {"product_name": "Aveeno Daily Moisturizing Lotion", "brand": "Aveeno", "category": "Body Lotion", "description": "Colloidal oatmeal body lotion for dry, itchy skin", "key_ingredients": ["Colloidal Oatmeal", "Glycerin", "Dimethicone"], "skin_types": ["Dry", "Normal", "Sensitive"], "skin_concerns": ["Dryness", "Itching", "Irritation"], "price_range": "$", "usage_frequency": "Daily", "expected_results": "1-2 Weeks"},
    {"product_name": "The Ordinary Glycolic Acid 7% Toning Solution", "brand": "The Ordinary", "category": "Exfoliant", "description": "Daily use glycolic acid toner for brighter skin", "key_ingredients": ["Glycolic Acid", "Aloe Vera", "Ginseng"], "skin_types": ["Oily", "Combination", "Normal"], "skin_concerns": ["Uneven Skin Tone", "Dark Spots", "Dullness"], "price_range": "$", "usage_frequency": "Once Daily (PM)", "expected_results": "4-8 Weeks"},
    {"product_name": "Innisfree Green Tea Seed Serum", "brand": "Innisfree", "category": "Serum", "description": "Hydrating serum with green tea seed oil", "key_ingredients": ["Green Tea Extract", "Hyaluronic Acid", "Glycerin"], "skin_types": ["Oily", "Combination", "Normal"], "skin_concerns": ["Dryness", "Dullness", "Uneven Skin Tone"], "price_range": "$", "usage_frequency": "Twice Daily", "expected_results": "2-4 Weeks"},
    {"product_name": "Dermalogica Daily Microfoliant", "brand": "Dermalogica", "category": "Exfoliant", "description": "Gentle rice-based exfoliating powder", "key_ingredients": ["Salicylic Acid", "Glycolic Acid", "Green Tea Extract"], "skin_types": ["Oily", "Combination", "Normal", "Sensitive"], "skin_concerns": ["Uneven Skin Tone", "Dullness", "Fine Lines"], "price_range": "$$", "usage_frequency": "Daily", "expected_results": "2-4 Weeks"},
    {"product_name": "First Aid Beauty Ultra Repair Cream", "brand": "First Aid Beauty", "category": "Moisturizer", "description": "Intensive moisturizer with colloidal oatmeal", "key_ingredients": ["Colloidal Oatmeal", "Shea Butter", "Allantoin"], "skin_types": ["Dry", "Normal", "Sensitive"], "skin_concerns": ["Dryness", "Irritation", "Itching"], "price_range": "$$", "usage_frequency": "As Needed", "expected_results": "1-2 Weeks"},
    {"product_name": "Summer Fridays Jet Lag Mask", "brand": "Summer Fridays", "category": "Face Mask", "description": "Hydrating and brightening mask with niacinamide", "key_ingredients": ["Niacinamide", "Glycerin", "Vitamin C"], "skin_types": ["Oily", "Dry", "Combination", "Normal"], "skin_concerns": ["Dryness", "Dullness", "Fine Lines"], "price_range": "$$", "usage_frequency": "2-3 Times Weekly", "expected_results": "1-2 Weeks"},
]


# ═══════════════════════════════════════════════════════════
# SKIN CONDITIONS
# ═══════════════════════════════════════════════════════════
SKIN_CONDITIONS_DATA = [
    {"condition_name": "Acne", "description": "Inflammatory skin condition with pimples, blackheads, and whiteheads", "recommended_ingredients": ["Salicylic Acid", "Niacinamide", "Benzoyl Peroxide", "Tea Tree Oil", "Zinc PCA", "Azelaic Acid", "Adapalene"], "avoid_ingredients": ["Coconut Oil", "Isopropyl Myristate", "Mineral Oil", "Shea Butter"], "severity_factors": ["hormonal", "bacterial", "excess_oil"]},
    {"condition_name": "Pimples", "description": "Inflamed spots caused by clogged pores", "recommended_ingredients": ["Salicylic Acid", "Niacinamide", "Benzoyl Peroxide", "Zinc PCA", "Tea Tree Oil"], "avoid_ingredients": ["Coconut Oil", "Isopropyl Myristate", "Fragrance"], "severity_factors": ["bacterial", "clogged_pores"]},
    {"condition_name": "Dark Spots", "description": "Post-inflammatory hyperpigmentation or sun spots", "recommended_ingredients": ["Vitamin C", "Alpha Arbutin", "Niacinamide", "Tranexamic Acid", "Kojic Acid", "Azelaic Acid"], "avoid_ingredients": ["Hydroquinone"], "severity_factors": ["sun_exposure", "inflammation"]},
    {"condition_name": "Hyperpigmentation", "description": "Excess melanin causing darker patches of skin", "recommended_ingredients": ["Vitamin C", "Alpha Arbutin", "Niacinamide", "Tranexamic Acid", "Azelaic Acid", "Glycolic Acid", "Licorice Root Extract"], "avoid_ingredients": ["Fragrance", "Essential Oils"], "severity_factors": ["sun_exposure", "hormonal", "inflammation"]},
    {"condition_name": "Redness", "description": "Persistent facial redness or flushing", "recommended_ingredients": ["Centella Asiatica", "Green Tea Extract", "Niacinamide", "Aloe Vera", "Chamomile Extract", "Allantoin"], "avoid_ingredients": ["Alcohol Denat", "Fragrance", "Essential Oils", "Witch Hazel", "Retinol"], "severity_factors": ["sensitivity", "inflammation", "rosacea"]},
    {"condition_name": "Dryness", "description": "Lack of moisture in the skin, flaking, tight feeling", "recommended_ingredients": ["Hyaluronic Acid", "Glycerin", "Ceramides", "Squalane", "Shea Butter", "Panthenol", "Colloidal Oatmeal"], "avoid_ingredients": ["Alcohol Denat", "Salicylic Acid", "Benzoyl Peroxide", "Sulfur", "Witch Hazel"], "severity_factors": ["barrier_damage", "environmental", "overwashing"]},
    {"condition_name": "Itching", "description": "Persistent skin itchiness, potentially indicating irritation", "recommended_ingredients": ["Colloidal Oatmeal", "Aloe Vera", "Ceramides", "Centella Asiatica", "Panthenol"], "avoid_ingredients": ["Fragrance", "Essential Oils", "Sodium Lauryl Sulfate", "Alcohol Denat"], "severity_factors": ["allergy", "dryness", "irritation"]},
    {"condition_name": "Irritation", "description": "Skin sensitivity, stinging, or burning sensation", "recommended_ingredients": ["Centella Asiatica", "Aloe Vera", "Panthenol", "Ceramides", "Allantoin", "Chamomile Extract"], "avoid_ingredients": ["Fragrance", "Essential Oils", "Alcohol Denat", "Sodium Lauryl Sulfate", "Retinol", "Glycolic Acid"], "severity_factors": ["barrier_damage", "allergy", "overuse_of_actives"]},
    {"condition_name": "Blackheads", "description": "Open comedones caused by clogged pores", "recommended_ingredients": ["Salicylic Acid", "Niacinamide", "Glycolic Acid", "Bentonite Clay", "Charcoal"], "avoid_ingredients": ["Coconut Oil", "Isopropyl Myristate", "Mineral Oil"], "severity_factors": ["excess_oil", "dead_skin"]},
    {"condition_name": "Whiteheads", "description": "Closed comedones from clogged pores", "recommended_ingredients": ["Salicylic Acid", "Adapalene", "Glycolic Acid", "Niacinamide"], "avoid_ingredients": ["Coconut Oil", "Isopropyl Myristate"], "severity_factors": ["excess_oil", "dead_skin"]},
    {"condition_name": "Fine Lines", "description": "Early signs of aging, shallow wrinkles", "recommended_ingredients": ["Retinol", "Peptides", "Hyaluronic Acid", "Vitamin C", "Bakuchiol", "Niacinamide"], "avoid_ingredients": ["Alcohol Denat"], "severity_factors": ["aging", "sun_damage", "dehydration"]},
    {"condition_name": "Wrinkles", "description": "Deep lines and creases in the skin from aging", "recommended_ingredients": ["Retinol", "Peptides", "Hyaluronic Acid", "Vitamin C", "Coenzyme Q10", "Bakuchiol"], "avoid_ingredients": ["Alcohol Denat"], "severity_factors": ["aging", "sun_damage", "collagen_loss"]},
    {"condition_name": "Uneven Skin Tone", "description": "Irregular skin coloring, patches of different shades", "recommended_ingredients": ["Vitamin C", "Niacinamide", "Alpha Arbutin", "Glycolic Acid", "Lactic Acid", "Azelaic Acid"], "avoid_ingredients": ["Fragrance"], "severity_factors": ["sun_exposure", "post_inflammatory"]},
]


async def seed_database():
    """Seed the database with initial data."""
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with async_session_maker() as session:
        # Check if data already exists
        result = await session.execute(select(Ingredient).limit(1))
        if result.scalar_one_or_none():
            print("⚠️  Database already seeded, skipping...")
            return

        print("🌱 Seeding ingredients...")
        for data in INGREDIENTS_DATA:
            ingredient = Ingredient(**data)
            session.add(ingredient)

        print("🌱 Seeding products...")
        for data in PRODUCTS_DATA:
            product = Product(**data)
            session.add(product)

        print("🌱 Seeding skin conditions...")
        for data in SKIN_CONDITIONS_DATA:
            condition = SkinCondition(**data)
            session.add(condition)

        await session.commit()
        print(f"✅ Seeded {len(INGREDIENTS_DATA)} ingredients, {len(PRODUCTS_DATA)} products, {len(SKIN_CONDITIONS_DATA)} conditions")


if __name__ == "__main__":
    asyncio.run(seed_database())
